import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:skin_analysis_app/screens/already_login_screen.dart';
import '../Bloc/auth_bloc.dart';
import '../Bloc/auth_state.dart';
import '../Bloc/auth_event.dart';
import 'settings_screen.dart';
import 'analysis_type_screen.dart';

class LoginPage extends StatefulWidget {
  const LoginPage({super.key});

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> with SingleTickerProviderStateMixin {
    // STEP 2 — ADD STRING CONSTANTS
    final String termsText = '''
  By using this application, you agree to the following terms and conditions.

  1. Purpose of the App

  The Youv.Ai app provides AI-based skin analysis and related insights for educational and informational purposes only.

  The results, images, or recommendations generated by the application are not medical advice, diagnosis, or treatment.

  Always consult a licensed dermatologist or healthcare professional for any medical concerns.

  2. Eligibility

  You must be at least 18 years old to use the app, or have parental/guardian consent if under 18.

  By using the app, you confirm that all information you provide is accurate and truthful.

  3. Use of AI-Generated Content

  All analysis, reports, and visual outputs (including “before/after” simulations) are generated using artificial intelligence and may not fully reflect actual results.

  The app does not guarantee the accuracy or completeness of analysis or outcomes.

  AI-generated outputs must not be considered a substitute for professional medical consultation.

  4. Data Collection and Privacy

  We collect and process facial images for AI skin analysis purposes.

  Your personal data is protected under our Privacy Policy.

  We do not share your data with third parties without your consent, except where required for service operation or by law.

  5. Medical Disclaimer

  This application provides general skin analysis and recommendations.

  It is not a substitute for professional medical advice.

  Always consult a dermatologist for serious skin concerns.

  6. User Responsibilities

  • You must provide accurate information.
  • You are responsible for maintaining the confidentiality of your account.
  • You agree not to misuse the application or its features.

  7. Service Availability

  We strive to maintain service availability but cannot guarantee uninterrupted access.

  We may update, modify, or discontinue parts of the service at any time without prior notice.
  ''';

      final String privacyText = '''
        This Privacy Policy explains how we collect, use, and protect your information when you use our App.

        1. Information We Collect

           Personal details you provide.
           Facial images uploaded for AI skin analysis.
           Device and usage data collected automatically.

        2. How We Use Your Information

           To generate AI-based skin analysis and visual outputs.
           To improve app performance, features, and user experience.
           To provide customer support and ensure safety.

        3. Image Processing

           Images are processed securely and may be stored temporarily.
           We do not sell your personal data or images.
           You can request deletion of your images at any time.

        4. Data Sharing

        We share information only with:

          Trusted service providers (AI processing, cloud storage, payments).
          Legal authorities when required by law.

        We never sell your data to third parties.
    ''';

    // STEP 1 — ADD DIALOG FUNCTION
    void _showPolicyDialog({
      required String title,
      required String content,
    }) {
      showDialog(
        context: context,
        builder: (context) => Dialog(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          child: ConstrainedBox(
            constraints: BoxConstraints(maxHeight: 600),
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 24, horizontal: 20),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    title,
                    textAlign: TextAlign.center,
                    style: GoogleFonts.lora(
                      fontSize: 25,
                      fontWeight: FontWeight.w900,
                      color: const Color(0xFF3A2A22),
                      letterSpacing: 0.2,
                    ),
                  ),
                  const SizedBox(height: 18),
                  Expanded(
                    child: SingleChildScrollView(
                      child: Text(
                        content,
                        style: GoogleFonts.lora(
                          fontSize: 14,
                          color: const Color(0xFF3A2A22),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(height: 18),
                  SizedBox(
                    width: double.infinity,
                    child: TextButton(
                      onPressed: () => Navigator.pop(context),
                      child: const Text('Close', style: TextStyle(color: Color(0xFFE8B4BA))),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      );
    }
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController(text: '+');
  final TextEditingController _cityController = TextEditingController();
  final TextEditingController _citySearchController = TextEditingController();
  final List<String> _cities = [
    'Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan',
    'Suwon', 'Changwon', 'Goyang', 'Yongin', 'Seongnam', 'Bucheon', 'Ansan',
    'Cheongju', 'Jeonju', 'Cheonan', 'Pohang', 'Jeju City', 'Gimhae',
    'Hwaseong', 'Anyang', 'Pyeongtaek', 'Siheung', 'Uijeongbu', 'Paju',
    'Gumi', 'Wonju', 'Asan', 'Iksan', 'Mokpo', 'Suncheon', 'Gangneung',
    'Chuncheon', 'Andong', 'Geoje', 'Tongyeong', 'Yeosu', 'Gyeongju',
    'Namyangju', 'Gwangmyeong', 'Gunpo', 'Osan', 'Yangsan', 'Jecheon',
    'Nonsan', 'Sacheon', 'Miryang', 'Donghae'
  ];
  String? _selectedCity;
  final bool _showCitySearch = false;
  bool _consent = false;
  bool _isSendingOtp = false;
  late final AuthBloc _authBloc;
  late AnimationController _animController;
  late Animation<double> _fadeAnim;
  late Animation<Offset> _slideAnim;
  
  Color? get lowMutedText => null;
  
  Color? get headlineText => null;

  @override
  void initState() {
    super.initState();
    _authBloc = AuthBloc();
    _animController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 250),
    );
    _fadeAnim = CurvedAnimation(parent: _animController, curve: Curves.easeOut);
    _slideAnim = Tween<Offset>(begin: const Offset(0, 0.06), end: Offset.zero)
        .animate(CurvedAnimation(parent: _animController, curve: Curves.easeOut));
    _animController.forward();
  }

  @override
  void dispose() {
    _authBloc.close();
    _animController.dispose();
    _nameController.dispose();
    _phoneController.dispose();
    _cityController.dispose();
    super.dispose();
  }

  String _normalizedPhone() {
    return _phoneController.text.trim();
  }

  void _requestOtpForSignup() {
    final phone = _normalizedPhone();
    final digits = phone.replaceAll(RegExp(r'[^0-9]'), '');
    if (digits.length < 5) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a valid mobile number')),
      );
      return;
    }

    _authBloc.add(
      SendOtpRequested(phone: phone, flow: 'signup'),
    );
  }

  @override
  Widget build(BuildContext context) {
    final W = MediaQuery.of(context).size.width;
    final H = MediaQuery.of(context).size.height;
    final compactScale = (H / 900.0).clamp(0.90, 1.0).toDouble();
    final horizontalPadding = (W * 0.06 * compactScale).clamp(16.0, 24.0).toDouble();
    final topSpacing = (H * 0.05 * compactScale).clamp(14.0, 34.0).toDouble();
    final betweenLabelHeading = (H * 0.018 * compactScale).clamp(8.0, 16.0).toDouble();
    final betweenHeadingSub = (H * 0.012 * compactScale).clamp(6.0, 12.0).toDouble();
    final betweenSubCard = (H * 0.026 * compactScale).clamp(10.0, 20.0).toDouble();
    final cardPadding = (W * 0.04 * compactScale).clamp(10.0, 16.0).toDouble();
    final cardRadius = W * 0.05;
    final fieldSpacing = (H * 0.015 * compactScale).clamp(8.0, 14.0).toDouble();
    final labelInputGap = (H * 0.007 * compactScale).clamp(4.0, 9.0).toDouble();
    final inputHeight = (H * 0.056 * compactScale).clamp(38.0, 50.0).toDouble();
    final consentSpacing = (H * 0.018 * compactScale).clamp(8.0, 14.0).toDouble();
    final buttonSpacing = (H * 0.018 * compactScale).clamp(8.0, 14.0).toDouble();
    final buttonHeight = (H * 0.058 * compactScale).clamp(42.0, 52.0).toDouble();
    final checkboxSize = W * 0.045 > 18 ? W * 0.045 : 18.0;

    return BlocProvider.value(
      value: _authBloc,
      child: BlocListener<AuthBloc, AuthState>(
        listener: (context, state) {
          if (state is AuthLoading) {
            if (!_isSendingOtp) {
              setState(() => _isSendingOtp = true);
            }
          } else {
            if (_isSendingOtp) {
              setState(() => _isSendingOtp = false);
            }
          }

          if (state is AuthMessage) {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (_) => BlocProvider.value(
                  value: _authBloc,
                  child: OTPVerificationScreen(
                    phone: _normalizedPhone(),
                    name: _nameController.text.trim(),
                    city: _selectedCity ?? '',
                  ),
                ),
              ),
            );
          } else if (state is AuthError) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text(state.error)),
            );
          }
        },
        child: SafeArea(
          child: Scaffold(
        backgroundColor: const Color(0xFFF9F0EC),
        resizeToAvoidBottomInset: true,
        body: LayoutBuilder(
          builder: (context, viewport) {
            return SingleChildScrollView(
              physics: const BouncingScrollPhysics(),
              padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
              child: ConstrainedBox(
                constraints: BoxConstraints(minHeight: viewport.maxHeight),
                child: IntrinsicHeight(
                  child: Center(
                    child: ConstrainedBox(
                      constraints: const BoxConstraints(maxWidth: 420),
                      child: Padding(
                        padding: EdgeInsets.symmetric(horizontal: horizontalPadding),
                        child: FadeTransition(
                          opacity: _fadeAnim,
                          child: SlideTransition(
                            position: _slideAnim,
                            child: Column(
                      mainAxisSize: MainAxisSize.max,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Expanded(
                          child: Padding(
                            padding: EdgeInsets.only(
                              top: topSpacing,
                              bottom: betweenSubCard,
                            ),
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Text(
                                  'AI FACIAL ANALYSIS',
                                  textAlign: TextAlign.center,
                                  style: GoogleFonts.lora(
                                    fontSize: 12.5,
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: 2.0,
                                    color: lowMutedText ?? const Color(0xFFA89B93),
                                  ),
                                ),
                                SizedBox(height: betweenLabelHeading),
                                Text(
                                  'Create Your Analysis Profile',
                                  textAlign: TextAlign.center,
                                  style: GoogleFonts.lora(
                                    fontSize: (27 * compactScale).clamp(22.0, 30.0).toDouble(),
                                    fontWeight: FontWeight.w600,
                                    height: 1.3,
                                    color: headlineText,
                                  ),
                                ),
                                SizedBox(height: betweenHeadingSub),
                                Padding(
                                  padding: const EdgeInsets.symmetric(horizontal: 8.0),
                                  child: Text(
                                    'Your personalized report will be securely stored under this profile.',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: (W * 0.039 * compactScale).clamp(13.0, 16.5).toDouble(),
                                      color: const Color(0xFFB0B0B0),
                                      fontWeight: FontWeight.w400,
                                    ),
                                    maxLines: 2,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Container(
                          width: double.infinity,
                          decoration: BoxDecoration(
                            color: const Color(0xFFFFFBF7),
                            borderRadius: BorderRadius.circular(cardRadius),
                            boxShadow: const [
                              BoxShadow(
                                color: Color(0x1A000000),
                                blurRadius: 18,
                                offset: Offset(0, 4),
                              ),
                            ],
                          ),
                          padding: EdgeInsets.all(cardPadding),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.stretch,
                            children: [
                              // Full Name Card
                              Container(
                                margin: EdgeInsets.only(bottom: fieldSpacing),
                                padding: EdgeInsets.all(8 * compactScale),
                                decoration: BoxDecoration(
                                  color: Colors.white,
                                  borderRadius: BorderRadius.circular(14),
                                  boxShadow: [
                                    BoxShadow(
                                      color: Colors.black12,
                                      blurRadius: 4,
                                      offset: const Offset(0, 1),
                                    ),
                                  ],
                                ),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text('Full Name', style: TextStyle(fontSize: (14.5 * compactScale).clamp(12.5, 16.0).toDouble(), color: Colors.black87, fontWeight: FontWeight.w500)),
                                    SizedBox(height: labelInputGap),
                                    TextField(
                                      controller: _nameController,
                                      style: TextStyle(
                                        fontSize: (15 * compactScale).clamp(13.0, 16.0).toDouble(),
                                      ),
                                      decoration: InputDecoration(
                                        hintText: 'Enter your name',
                                        isDense: true,
                                        contentPadding: EdgeInsets.symmetric(
                                          horizontal: 12,
                                          vertical: (11 * compactScale).clamp(9.0, 13.0).toDouble(),
                                        ),
                                        border: OutlineInputBorder(
                                          borderRadius: BorderRadius.circular(12),
                                          borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
                                        ),
                                        filled: true,
                                        fillColor: Colors.white,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              // Mobile Number Card
                              Container(
                                margin: EdgeInsets.only(bottom: fieldSpacing),
                                padding: EdgeInsets.all(8 * compactScale),
                                decoration: BoxDecoration(
                                  color: Colors.white,
                                  borderRadius: BorderRadius.circular(14),
                                  boxShadow: [
                                    BoxShadow(
                                      color: Colors.black12,
                                      blurRadius: 4,
                                      offset: const Offset(0, 1),
                                    ),
                                  ],
                                ),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text('Mobile Number', style: TextStyle(fontSize: (14.5 * compactScale).clamp(12.5, 16.0).toDouble(), color: Colors.black87, fontWeight: FontWeight.w500)),
                                    SizedBox(height: labelInputGap),
                                    TextField(
                                      controller: _phoneController,
                                      keyboardType: TextInputType.phone,
                                      style: TextStyle(
                                        fontSize: (15 * compactScale).clamp(13.0, 16.0).toDouble(),
                                      ),
                                      decoration: InputDecoration(
                                        hintText: 'Enter your mobile number',
                                        isDense: true,
                                        contentPadding: EdgeInsets.symmetric(
                                          horizontal: 12,
                                          vertical: (11 * compactScale).clamp(9.0, 13.0).toDouble(),
                                        ),
                                        border: OutlineInputBorder(
                                          borderRadius: BorderRadius.circular(12),
                                          borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
                                        ),
                                        filled: true,
                                        fillColor: Colors.white,
                                      ),
                                    ),
                                    SizedBox(height: (3 * compactScale).clamp(2.0, 4.0)),
                                    Text('OTP verification required.', style: TextStyle(fontSize: (12 * compactScale).clamp(10.5, 13.0).toDouble(), color: Colors.black54)),
                                  ],
                                ),
                              ),
                              // City Card with Dropdown
                              Container(
                                margin: EdgeInsets.only(bottom: fieldSpacing),
                                padding: EdgeInsets.all(8 * compactScale),
                                decoration: BoxDecoration(
                                  color: Colors.white,
                                  borderRadius: BorderRadius.circular(14),
                                  boxShadow: [
                                    BoxShadow(
                                      color: Colors.black12,
                                      blurRadius: 4,
                                      offset: const Offset(0, 1),
                                    ),
                                  ],
                                ),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text('City', style: TextStyle(fontSize: (14.5 * compactScale).clamp(12.5, 16.0).toDouble(), color: Colors.black87, fontWeight: FontWeight.w500)),
                                    SizedBox(height: labelInputGap),
                                    DropdownButtonFormField<String>(
                                      initialValue: _selectedCity,
                                      items: _cities.map((city) => DropdownMenuItem(
                                        value: city,
                                        child: Text(city),
                                      )).toList(),
                                      onChanged: (value) {
                                        setState(() {
                                          _selectedCity = value;
                                          _cityController.text = value ?? '';
                                        });
                                      },
                                      decoration: InputDecoration(
                                        hintText: 'Select your city',
                                        isDense: true,
                                        contentPadding: EdgeInsets.symmetric(
                                          horizontal: 12,
                                          vertical: (11 * compactScale).clamp(9.0, 13.0).toDouble(),
                                        ),
                                        border: OutlineInputBorder(
                                          borderRadius: BorderRadius.circular(12),
                                          borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
                                        ),
                                        filled: true,
                                        fillColor: Colors.white,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              SizedBox(height: consentSpacing),
                              Row(
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  SizedBox(
                                    width: checkboxSize,
                                    height: checkboxSize,
                                    child: Checkbox(
                                      value: _consent,
                                      onChanged: (v) => setState(() => _consent = v ?? false),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(5),
                                      ),
                                      side: const BorderSide(color: Color(0xFFB0B0B0), width: 1),
                                      activeColor: const Color(0xFFE8B4BA),
                                      materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                      visualDensity: VisualDensity.compact,
                                    ),
                                  ),
                                  const SizedBox(width: 10),
                                  Expanded(
                                    child: Wrap(
                                      crossAxisAlignment: WrapCrossAlignment.center,
                                      children: [
                                        Text(
                                          'I agree to the ',
                                          style: TextStyle(
                                            fontSize: (W * 0.030 * compactScale).clamp(11.0, 13.0).toDouble(),
                                            
                                            color: const Color(0xFF8C8C8C),
                                          ),
                                        ),
                                        GestureDetector(
                                          onTap: () {
                                            _showPolicyDialog(
                                              title: "Terms of Use",
                                              content: termsText,
                                            );
                                          },
                                          child: Text(
                                            'Terms',
                                            style: TextStyle(
                                              fontSize: (W * 0.033 * compactScale).clamp(11.5, 14.0).toDouble(),
                                              color: const Color(0xFFE8B4BA),
                                              decoration: TextDecoration.underline,
                                            ),
                                          ),
                                        ),
                                        Text(
                                          ' & ',
                                          style: TextStyle(
                                            fontSize: (W * 0.033 * compactScale).clamp(11.5, 14.0).toDouble(),
                                            color: const Color(0xFF8C8C8C),
                                          ),
                                        ),
                                        GestureDetector(
                                          onTap: () {
                                            _showPolicyDialog(
                                              title: "Privacy Policy",
                                              content: privacyText,
                                            );
                                          },
                                          child: Text(
                                            'Privacy Policy',
                                            style: TextStyle(
                                              fontSize: (W * 0.033 * compactScale).clamp(11.5, 14.0).toDouble(),
                                              color: const Color(0xFFE8B4BA),
                                              decoration: TextDecoration.underline,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                              SizedBox(height: buttonSpacing),
                              // Verify & Start Scan Button
                              Builder(
                                builder: (context) {
                                  final allFilled = _nameController.text.trim().isNotEmpty &&
                                      _phoneController.text.trim().isNotEmpty &&
                                      _selectedCity != null && _selectedCity!.trim().isNotEmpty && _consent;
                                  final anyFilled = _nameController.text.trim().isNotEmpty ||
                                      _phoneController.text.trim().isNotEmpty ||
                                      (_selectedCity != null && _selectedCity!.trim().isNotEmpty);
                                  return Column(
                                    crossAxisAlignment: CrossAxisAlignment.stretch,
                                    children: [
                                      ElevatedButton(
                                        onPressed: (allFilled && !_isSendingOtp)
                                            ? _requestOtpForSignup
                                            : null,
                                        style: ElevatedButton.styleFrom(
                                          backgroundColor: allFilled
                                              ? const Color(0xFFE4B3B8)
                                              : Colors.grey.shade400,
                                          foregroundColor: Colors.white,
                                          elevation: 0,
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(24),
                                          ),
                                          minimumSize: Size(double.infinity, buttonHeight),
                                          padding: EdgeInsets.symmetric(
                                            vertical: (10 * compactScale).clamp(8.0, 12.0).toDouble(),
                                          ),
                                        ),
                                        child: _isSendingOtp
                                            ? const SizedBox(
                                                height: 22,
                                                width: 22,
                                                child: CircularProgressIndicator(
                                                  strokeWidth: 2,
                                                  color: Colors.white,
                                                ),
                                              )
                                            : Text('Verify & Start Scan', style: TextStyle(fontSize: (16.5 * compactScale).clamp(14.0, 17.5).toDouble(), fontWeight: FontWeight.w600)),
                                      ),
                                      SizedBox(height: (8 * compactScale).clamp(6.0, 10.0)),
                                      Center(
                                        child: GestureDetector(
                                          onTap: () {
                                            Navigator.of(context).push(
                                              MaterialPageRoute(
                                                builder: (_) => AlreadyLoginScreen(),
                                              ),
                                            );
                                          },
                                          child: Text(
                                            'Already registered user?',
                                            style: TextStyle(
                                              color: Colors.blueGrey.shade700,
                                              fontSize: (15 * compactScale).clamp(12.5, 16.0).toDouble(),
                                              fontWeight: FontWeight.w500,
                                              decoration: TextDecoration.underline,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  );
                                },
                              ),
                            ],
                          ),
                        ),
                        SizedBox(height: (H * 0.02).clamp(8.0, 16.0)),
                      ],
                    ),
                  ),
                ),
              ),
            ),
                  ),
                ),
              ),
            );
          },
        ),
          ),
        ),
      ),
    );
  }

  Widget _buildPhoneInputField(double W) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Phone Number',
          style: TextStyle(fontSize: 14, color: Colors.black87, fontWeight: FontWeight.w500),
        ),
        SizedBox(height: 6),
        TextField(
          controller: _phoneController,
          keyboardType: TextInputType.number,
          decoration: InputDecoration(
            prefixIcon: Padding(
              padding: const EdgeInsets.only(left: 10, right: 6),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Image.asset(
                    'assets/images/india_flag.png',
                    width: 22,
                    height: 18,
                    errorBuilder: (context, error, stackTrace) => const Icon(Icons.flag, size: 18, color: Colors.black26),
                  ),
                  SizedBox(width: 4),
                  Text('+91', style: TextStyle(fontSize: 14, color: Colors.black87)),
                ],
              ),
            ),
            hintText: 'Enter your phone number',
            floatingLabelBehavior: FloatingLabelBehavior.auto,
            contentPadding: const EdgeInsets.symmetric(vertical: 16, horizontal: 14),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(18),
              borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(18),
              borderSide: const BorderSide(color: Color(0xFFD4999F), width: 2),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(18),
              borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
            ),
            fillColor: Colors.white,
            filled: true,
          ),
        ),
      ],
    );
  }

  Widget _buildInputField({
    required String label,
    required TextEditingController controller,
    required TextInputType keyboardType,
    String? prefix,
    String? hint,
    double? labelFontSize,
    double? inputFontSize,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2.0),
      child: TextField(
        controller: controller,
        keyboardType: keyboardType,
        style: TextStyle(fontSize: inputFontSize ?? 15, color: Colors.black87),
        decoration: InputDecoration(
          labelText: label,
          labelStyle: TextStyle(
            fontSize: labelFontSize ?? 14,
            color: Colors.black54,
            fontWeight: FontWeight.w500,
          ),
          prefixText: prefix,
          hintText: hint,
          floatingLabelBehavior: FloatingLabelBehavior.auto,
          contentPadding: const EdgeInsets.symmetric(vertical: 18, horizontal: 16),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(18),
            borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(18),
            borderSide: const BorderSide(color: Color(0xFFD4999F), width: 2),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(18),
            borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
          ),
          filled: true,
          fillColor: Colors.white,
        ),
      ),
    );
  }

  Widget _buildCityDropdown(double W) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('City',
          style: TextStyle(fontSize: 14, color: Colors.black87, fontWeight: FontWeight.w500),
        ),
        // ...existing code...
      ],
    );
  }
}

// AdaptiveInputField widget
class AdaptiveInputField extends StatelessWidget {
  final String label;
  final TextEditingController controller;
  final TextInputType keyboardType;
  final double labelInputGap;
  final double inputHeight;
  final String? prefixText;
  final bool isPhone;
  final String? microText;

  const AdaptiveInputField({
    super.key,
    required this.label,
    required this.controller,
    required this.keyboardType,
    required this.labelInputGap,
    required this.inputHeight,
    this.prefixText,
    this.isPhone = false,
    this.microText,
  });

  @override
  Widget build(BuildContext context) {
    final W = MediaQuery.of(context).size.width;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(fontSize: 14, color: Colors.black87, fontWeight: FontWeight.w500),
        ),
        SizedBox(height: labelInputGap),
        UnderlineTextField(
          controller: controller,
          keyboardType: keyboardType,
          inputHeight: inputHeight,
          prefixText: prefixText,
          isPhone: isPhone,
        ),
        if (microText != null)
          Padding(
            padding: const EdgeInsets.only(top: 4),
            child: Text(
              microText!,
              style: TextStyle(
                fontSize: W * 0.028,
                color: const Color(0xFF8C8C8C).withOpacity(0.7),
                fontWeight: FontWeight.w400,
              ),
            ),
          ),
      ],
    );
  }
}

class UnderlineTextField extends StatefulWidget {
  final TextEditingController controller;
  final TextInputType keyboardType;
  final double inputHeight;
  final String? prefixText;
  final bool isPhone;

  const UnderlineTextField({
    super.key,
    required this.controller,
    required this.keyboardType,
    required this.inputHeight,
    this.prefixText,
    this.isPhone = false,
  });

  @override
  State<UnderlineTextField> createState() => _UnderlineTextFieldState();
}

class _UnderlineTextFieldState extends State<UnderlineTextField> with SingleTickerProviderStateMixin {
  late FocusNode _focusNode;
  late AnimationController _animController;
  late Animation<double> _underlineAnim;

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();
    _animController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 220),
    );
    _underlineAnim = Tween<double>(begin: 0, end: 1).animate(
      CurvedAnimation(parent: _animController, curve: Curves.easeOut),
    );
    _focusNode.addListener(() {
      if (_focusNode.hasFocus) {
        _animController.forward();
      } else {
        _animController.reverse();
      }
    });
  }

  @override
  void dispose() {
    _focusNode.dispose();
    _animController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final W = constraints.maxWidth;
        return Column(
          children: [
            SizedBox(
              height: widget.inputHeight,
              child: TextField(
                controller: widget.controller,
                focusNode: _focusNode,
                keyboardType: widget.keyboardType,
                style: TextStyle(
                  fontSize: W * 0.040,
                  color: Colors.black87,
                  fontWeight: FontWeight.w400,
                ),
                decoration: InputDecoration(
                  isDense: true,
                  border: InputBorder.none,
                  prefixText: widget.prefixText,
                  prefixStyle: TextStyle(
                    fontSize: W * 0.040,
                    color: Colors.black87,
                    fontWeight: FontWeight.w400,
                  ),
                  contentPadding: EdgeInsets.zero,
                ),
                cursorColor: const Color(0xFFE8B4BA),
                textInputAction: TextInputAction.next,
                inputFormatters: widget.isPhone
                    ? [
                        // Only allow numbers after +91
                      ]
                    : null,
              ),
            ),
            AnimatedBuilder(
              animation: _underlineAnim,
              builder: (context, child) {
                return Align(
                  alignment: Alignment.centerLeft,
                  child: Container(
                    height: 2,
                    width: W * 0.88 * _underlineAnim.value,
                    decoration: BoxDecoration(
                      color: _focusNode.hasFocus ? const Color(0xFFE8B4BA) : const Color(0xFFB0B0B0).withOpacity(0.4),
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                );
              },
            ),
          ],
        );
      },
    );
  }
}

class PrimaryCTAButton extends StatelessWidget {
  final String text;
  final bool enabled;
  final double height;
  final VoidCallback? onPressed;

  const PrimaryCTAButton({
    super.key,
    required this.text,
    required this.enabled,
    required this.height,
    this.onPressed,
  });

  @override
  Widget build(BuildContext context) {
    final W = MediaQuery.of(context).size.width;
    return AnimatedOpacity(
      duration: const Duration(milliseconds: 180),
      opacity: enabled ? 1 : 0.5,
      child: GestureDetector(
        onTap: enabled ? onPressed : null,
        child: Container(
          height: height,
          width: double.infinity,
          decoration: BoxDecoration(
            gradient: const LinearGradient(
              colors: [Color(0xFFE8B4BA), Color(0xFFF3D1D8)],
              begin: Alignment.centerLeft,
              end: Alignment.centerRight,
            ),
            borderRadius: BorderRadius.circular(height / 2),
          ),
          alignment: Alignment.center,
          child: Text(
            text,
            style: TextStyle(
              fontSize: W * 0.045,
              color: Colors.white,
              fontWeight: FontWeight.w600,
              letterSpacing: 0.2,
            ),
          ),
        ),
      ),
    );
  }
}

class OTPVerificationScreen extends StatefulWidget {
  final String phone;
  final String name;
  final String city;

  const OTPVerificationScreen({
    super.key,
    required this.phone,
    required this.name,
    required this.city,
  });

  @override
  State<OTPVerificationScreen> createState() => _OTPVerificationScreenState();
}

class _OTPVerificationScreenState extends State<OTPVerificationScreen> {
  final List<TextEditingController> _otpControllers = List.generate(6, (_) => TextEditingController());
  bool _loading = false;
  String _error = '';
  int _timer = 30;

  @override
  void initState() {
    super.initState();
    _startTimer();
  }

  void _startTimer() {
    Future.delayed(const Duration(seconds: 1), () {
      if (_timer > 0 && mounted) {
        setState(() => _timer--);
        _startTimer();
      }
    });
  }

  void _verifyOtp() {
    final otp = _otpControllers.map((c) => c.text).join();
    if (otp.length != 6) {
      setState(() => _error = 'Please enter the 6-digit OTP');
      return;
    }

    setState(() { _loading = true; });
    context.read<AuthBloc>().add(
      VerifyLoginMobile(
        phone: widget.phone,
        name: widget.name,
        email: '',
        password: '',
        otp: otp,
      ),
    );
  }

  void _resendCode() {
    setState(() { _timer = 30; });
    _startTimer();
    context.read<AuthBloc>().add(
      SendOtpRequested(phone: widget.phone, flow: 'signup'),
    );
  }

  @override
  Widget build(BuildContext context) {
    final W = MediaQuery.of(context).size.width;
    return BlocListener<AuthBloc, AuthState>(
      listener: (context, state) {
        if (state is AuthLoading) {
          setState(() {
            _loading = true;
            _error = '';
          });
        } else if (state is AuthAuthenticated) {
          setState(() => _loading = false);
          Navigator.pushReplacement(
            context,
            MaterialPageRoute(builder: (_) => AnalysisTypeScreen()),
          );
        } else if (state is AuthMessage) {
          setState(() => _loading = false);
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(state.message)),
          );
        } else if (state is AuthError) {
          setState(() {
            _loading = false;
            _error = state.error;
          });
        }
      },
      child: Scaffold(
        backgroundColor: const Color(0xFFF9F0EC),
        body: SafeArea(
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: W * 0.07, vertical: 40),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(height: 30),
              Text('Verify Your Number',
                style: GoogleFonts.poppins(
                  fontSize: W * 0.06,
                  fontWeight: FontWeight.w700,
                  color: Colors.black87,
                ),
              ),
              SizedBox(height: 12),
              Text('Enter the 6-digit code sent to +91 ${widget.phone}',
                style: GoogleFonts.poppins(
                  fontSize: W * 0.035,
                  color: Colors.black54,
                ),
              ),
              SizedBox(height: 32),
              Center(
                child: Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  alignment: WrapAlignment.center,
                  children: List.generate(6, (i) => _buildOtpBox(i)),
                ),
              ),
              if (_error.isNotEmpty)
                Padding(
                  padding: const EdgeInsets.only(top: 12),
                  child: Text(_error, style: const TextStyle(color: Colors.red)),
                ),
              SizedBox(height: 32),
              Row(
                children: [
                  TextButton(
                    onPressed: _timer == 0 ? _resendCode : null,
                    child: Text(
                      _timer == 0 ? 'Resend Code' : 'Resend in $_timer s',
                      style: GoogleFonts.poppins(
                        fontSize: W * 0.032,
                        color: Colors.black,
                      ),
                    ),
                  ),
                ],
              ),
              SizedBox(height: 32),
              SizedBox(
                width: double.infinity,
                height: 52,
                child: ElevatedButton(
                  onPressed: !_loading ? _verifyOtp : null,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFFE4B3B8),
                    foregroundColor: Colors.black87,
                    elevation: 4,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
                  ),
                  child: _loading
                      ? const CircularProgressIndicator()
                      : Text('Verify & Start Scan',
                          style: GoogleFonts.poppins(
                            fontSize: W * 0.045,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                ),
              ),
            ],
          ),
        ),
        ),
      ),
    );
  }

  Widget _buildOtpBox(int i) {
    return SizedBox(
      width: 44,
      child: TextField(
        controller: _otpControllers[i],
        keyboardType: TextInputType.number,
        maxLength: 1,
        textAlign: TextAlign.center,
        style: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w600),
        decoration: InputDecoration(
          counterText: '',
          isDense: true,
          contentPadding: const EdgeInsets.symmetric(vertical: 14),
          filled: true,
          fillColor: Colors.white,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: const BorderSide(color: Color(0xFF6B3A3A), width: 1.8),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: const BorderSide(color: Color(0xFFE6E2DD)),
          ),
        ),
        onChanged: (v) {
          if (v.isNotEmpty && i < 5) {
            FocusScope.of(context).nextFocus();
          } else if (v.isEmpty && i > 0) {
            FocusScope.of(context).previousFocus();
          }
          if (_otpControllers.every((c) => c.text.isNotEmpty)) {
            _verifyOtp();
          }
        },
      ),
    );
  }
}

class LoginPageContent extends StatefulWidget {
  const LoginPageContent({super.key});

  @override
  State<LoginPageContent> createState() => _LoginPageContentState();
}

class _LoginPageContentState extends State<LoginPageContent> {
  bool _isLoading = false;
  String _errorMessage = '';

  void _handleGoogleLogin() async {
    setState(() {
      _isLoading = true;
      _errorMessage = '';
    });

    try {
      final GoogleAuthProvider googleProvider = GoogleAuthProvider();

      final UserCredential userCredential =
          await FirebaseAuth.instance.signInWithPopup(googleProvider);

      if (userCredential.user != null) {
        final user = userCredential.user!;

        if (mounted) {
          context.read<AuthBloc>().add(
                GoogleLoginRequested(
                  googleToken: user.uid,
                  email: user.email ?? '',
                  displayName: user.displayName ?? '',
                  uid: user.uid,
                  photoURL: user.photoURL ?? '',
                  phoneNumber: user.phoneNumber ?? '',
                ),
              );
        }
      } else {
        setState(() {
          _errorMessage = 'Sign-in was cancelled';
          _isLoading = false;
        });
      }
    } catch (e) {
      setState(() {
        _errorMessage = 'Google sign-in failed: ${e.toString()}';
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<AuthBloc, AuthState>(
      listener: (context, state) {
        if (state is AuthLoading) {
          setState(() {
            _isLoading = true;
            _errorMessage = '';
          });
        } else if (state is AuthAuthenticated) {
          setState(() {
            _isLoading = false;
          });

          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message),
              backgroundColor: Colors.green,
            ),
          );

          Future.delayed(const Duration(milliseconds: 500), () {
            if (mounted) {
              Navigator.pop(context, true);
            }
          });
        } else if (state is AuthError) {
          setState(() {
            _isLoading = false;
            _errorMessage = state.error;
          });
        }
      },
      child: Scaffold(
        backgroundColor: const Color(0xFFE8B4BA),
        appBar: AppBar(
          backgroundColor: const Color(0xFFD4999F),
          title: const Text(
            'Login',
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
          ),
          leading: IconButton(
            icon: const Icon(Icons.arrow_back, color: Colors.white),
            onPressed: () => Navigator.pop(context, false),
          ),
          actions: [
            IconButton(
              icon: const Icon(Icons.settings, color: Colors.white),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (_) => const SettingsScreen()),
                );
              },
            ),
          ],
          elevation: 0,
        ),
        body: SafeArea(
          child: SingleChildScrollView(
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 30),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Container(
                    padding: const EdgeInsets.all(20),
                    decoration: const BoxDecoration(
                      color: Colors.white,
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(
                      Icons.person,
                      size: 60,
                      color: Color(0xFFD4999F),
                    ),
                  ),
                  const SizedBox(height: 25),
                  const Text(
                    'Welcome!',
                    style: TextStyle(
                      fontSize: 28,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'Login to unlock your full skin analysis',
                    style: TextStyle(fontSize: 14, color: Colors.white70),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 35),
                  if (_errorMessage.isNotEmpty)
                    Container(
                      padding: const EdgeInsets.all(12),
                      margin: const EdgeInsets.only(bottom: 20),
                      decoration: BoxDecoration(
                        color: Colors.red.shade50,
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(color: Colors.red.shade200),
                      ),
                      child: Row(
                        children: [
                          Icon(
                            Icons.error_outline,
                            color: Colors.red.shade700,
                            size: 20,
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              _errorMessage,
                              style: TextStyle(
                                color: Colors.red.shade700,
                                fontSize: 13,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: OutlinedButton.icon(
                      onPressed: _isLoading ? null : _handleGoogleLogin,
                      icon: _isLoading
                          ? const SizedBox(
                              height: 22,
                              width: 22,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                valueColor:
                                    AlwaysStoppedAnimation<Color>(
                                  Color(0xFFD4999F),
                                ),
                              ),
                            )
                          : Image.asset(
                              'images/google.png',
                              height: 24,
                              width: 24,
                              errorBuilder: (context, error, stackTrace) {
                                return const Icon(
                                  Icons.login,
                                  size: 24,
                                  color: Color(0xFFD4999F),
                                );
                              },
                            ),
                      label: Text(
                        _isLoading
                            ? "Signing in..."
                            : "Login/Register with Google",
                        style: const TextStyle(
                          color: Color(0xFF444444),
                          fontWeight: FontWeight.w600,
                          fontSize: 16,
                        ),
                      ),
                      style: OutlinedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        side: const BorderSide(
                          color: Color(0xFFE2E2E2),
                          width: 1.2,
                        ),
                        backgroundColor: Colors.white,
                      ),
                    ),
                  ),
                  const SizedBox(height: 30),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: const [
                      Icon(
                        Icons.info_outline,
                        color: Colors.white,
                        size: 20,
                      ),
                      SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          'Sign in with your Google account to access your skin analysis reports and detailed insights.',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 13,
                            height: 1.4,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 30),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
